# Generated by Django 3.2.8 on 2022-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
