# Generated by Django 3.2.8 on 2022-06-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
