# Generated by Django 3.2.8 on 2022-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_verified',
            field=models.BooleanField(),
        ),
    ]
