# Generated by Django 3.2.8 on 2022-06-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Transit', 'In_Transit'), ('delivered', 'delivered')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('ngo', 'NGO'), ('medical', 'Medical'), ('startup', 'Startup')], default='ngo', max_length=25),
        ),
    ]
