# Generated by Django 3.2.8 on 2022-06-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_verification_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
    ]
