# Generated by Django 3.2.8 on 2022-06-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='qrcode_url',
            field=models.CharField(max_length=2500),
        ),
    ]
