# Generated by Django 3.2.8 on 2022-06-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_is_verified'),
        ('campaigns', '0013_alter_campaign_qrcode_url'),
    ]

    operations = [
    ]
