# Generated by Django 3.2.8 on 2022-06-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_merge_20220607_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='qrcode_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='qrcode_url',
            field=models.CharField(max_length=2800),
        ),
    ]
