# Generated by Django 3.2.8 on 2022-06-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_alter_campaign_qrcode_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='qrcode_id',
            new_name='asset_id',
        ),
    ]
