# Generated by Django 3.2.8 on 2022-06-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_rename_qrcode_id_campaign_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='asset_id',
            field=models.CharField(max_length=500),
        ),
    ]
