# Generated by Django 4.1.7 on 2023-07-16 09:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_remove_campaign_asset_id_remove_campaign_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='asset_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='qrcode_url',
            field=models.CharField(default=datetime.datetime(2023, 7, 16, 9, 53, 4, 887128, tzinfo=datetime.timezone.utc), max_length=2800),
            preserve_default=False,
        ),
    ]
